### ISSUE TITLE
missing ./blastdb_aliastool

### ISSUE THREAD

**Issue by LuBeifang** [btjaden/TargetRNA3#1]
I tired to install everything described in User_Manual, and this error occured.
FileNotFoundError: [Errno 2] No such file or directory: './blastdb_aliastool'

**Comment by LuBeifang** [comment]
THX！
Solved by：
download ncbi-blast-2.15.0+,
$ cp blastdb_aliastool blastp blastn <path to TargetRNA3>

Also mention here.
Downloading ViennaRNA sourcecode, then
$ ./configure

Also i tried to change the path in TargetRNA3.py.
This kind of missing file error was solved.

**Comment by LuBeifang** [comment]
But a new error occured.
Traceback (most recent call last):
  File "/home/lu/TargetRNA3/TargetRNA3.py", line 480, in <module>
    df_output, mRNA_info, sRNA_conservation = run_TargetRNA3(sRNA_name, sRNA_sequence)
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lu/TargetRNA3/TargetRNA3.py", line 465, in run_TargetRNA3
    y_pred_proba = predictions(X)
                   ^^^^^^^^^^^^^^
  File "/home/lu/TargetRNA3/TargetRNA3.py", line 374, in predictions
    model_info = pickle.load(in_file)
                 ^^^^^^^^^^^^^^^^^^^^
  File "sklearn/tree/_tree.pyx", line 676, in sklearn.tree._tree.Tree.__setstate__
  File "sklearn/tree/_tree.pyx", line 1364, in sklearn.tree._tree._check_node_ndarray
ValueError: node array from the pickle has an incompatible dtype:
- expected: [('left_child', '<i8'), ('right_child', '<i8'), ('feature', '<i8'), ('threshold', '<f8'), ('impurity', '<f8'), ('n_node_samples', '<i8'), ('weighted_n_node_samples', '<f8')]
- got     : {'names': ['left_child', 'right_child', 'feature', 'threshold', 'impurity', 'n_node_samples', 'weighted_n_node_samples', 'missing_go_to_left'], 'formats': ['<i8', '<i8', '<i8', '<f8', '<f8', '<i8', '<f8', 'u1'], 'offsets': [0, 8, 16, 24, 32, 40, 48, 56], 'itemsize': 64}

**Comment by btjaden** [comment]
Depending on what library versions you are using, it's possible the error is a function of your library version.
As a test, try executing the following code:
```
import pickle
with open('DataFiles/model.pickle', 'rb') as in_file: model_info = pickle.load(in_file)
```
Some users have reported problems executing the above code with older libraries, e.g., sklearn version 1.3 works but older versions such as sklearn version 1.2 may cause errors. You can check what sklearn version you are using with:
```
import sklearn
print(sklearn.__version__)
```
If this is the problem then try updating your library versions.
