### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by chengchengxinyi** [btjaden/TargetRNA3#3]
Hello.
When running TargetRNA3, I encountered an error.

multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/cxy/anaconda3/envs/py310/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/cxy/anaconda3/envs/py310/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/mnt/g/TargetRNA3/TargetRNA3.py", line 317, in run_RNAplex
    structure_info = p.stdout.decode().strip().split('\n')[2]
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/g/TargetRNA3/TargetRNA3.py", line 480, in <module>
    df_output, mRNA_info, sRNA_conservation = run_TargetRNA3(sRNA_name, sRNA_sequence)
  File "/mnt/g/TargetRNA3/TargetRNA3.py", line 463, in run_TargetRNA3
    energies, structure_data = get_interaction_energies(GENOME_DIR, SRNA_FILENAME, sRNA_name, sRNA_sequence)
  File "/mnt/g/TargetRNA3/TargetRNA3.py", line 334, in get_interaction_energies
    with multiprocessing.Pool() as pool: energy_list = pool.map(partial(run_RNAplex, GENOME_DIR, SRNA_FILENAME), mRNA_files)
  File "/home/cxy/anaconda3/envs/py310/lib/python3.10/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/cxy/anaconda3/envs/py310/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
IndexError: list index out of range

There were no errors when I ran two provided examples. However, when I ran local genome, I encountered an error. I modified the format of the genome information based on the files from the two examples, because we haven't uploaded this genome before，and there were no errors when I ran AddGenome. Could you please help me analyze what the problem might be? Thank you.

**Comment by btjaden** [comment]
The problem may be the output of RNAplex. TargetRNA3 uses the program RNAplex from the ViennaRNA package as part of its RNA interaction calculations. TargetRNA3 expects the output of RNAplex to be 3 lines and, from your error message, it looks like the output of RNAplex is less than 3 lines when using your local genome for some reason. Perhaps this is a result of your local genome and its gene annotations not being formatted as expected by TargetRNA3. To help you track down the issue, I suggest the following:

First, try running RNAplex with the provided examples. For instance, executing
`./RNAplex -f 0 -q SgrS.fa -t Genomes/GCF_000005845.2/RNAplfold_results/NC_000913.3____sgrR.fa Genomes/GCF_000005845.2/RNAplfold_results/ -b`

may yield the following output
```
>NC_000913.3____sgrR
>SgrS
(((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((.&))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))).   1,134 :   1,134 (-282.00) i:133,j:1 <-281.70>
```

Note, the above output is 3 lines. Now try running RNAplex on your own sRNA FASTA file and mRNA from your local genome and check if the output is 3 lines. It may be that all mRNAs from your local genome are causing problematic RNAplex output or only a subset of mRNAs, but the above experimentation may help illuminate if your local genome and its gene annotations are formatted correctly for TargetRNA3 and RNAplex.

**Comment by chengchengxinyi** [comment]
Thank you very much. Following your advice, I ran RNAplex and found that some RNAplfold_results could not be recognized by RNAplex. This was due to the presence of spaces in the "symbol" column of some genes in the feature_table.txt file of my local genome, causing their RNAplfold_results to not be recognized. After removing the spaces, the program ran successfully.
