### ISSUE TITLE
Note: scikit-learn version compatibility

### ISSUE THREAD

**Issue by meichelman** [btjaden/TargetRNA3#4]
Hi,

I initially tried running TargetRNA3.py with the most up to data packages installed (numpy, pandas, etc.) and was getting an error with sklearn. I believe I was using version 1.5. I uninstalled this version and reinstalled sklearn version 1.3.2. After doing this my error went away, and the program ran to completion.

This is not so much an issue but more a suggestion that may help others with the same issue.

**Comment by btjaden** [comment]
Good point. The model was developed (and saved with pickle) using an earlier version of sklearn and pickling/unpickling is not supported across different sklearn versions. As you note, sklearn version 1.3 works. The preferred solution is to use sklearn version 1.3. If you need to use sklearn version 1.5, as a work-around, a new version of the model has been added that can be used with sklearn version 1.5. The file is located at DataFiles/model.pickle.sklearn.1.5. Delete the local file DataFiles/model.pickle and rename DataFiles/model.pickle.sklearn.1.5 to be DataFiles/model.pickle. Thanks for pointing this out in case others have the same issue.
