### ISSUE TITLE
Question regarding running multiple sRNAs

### ISSUE THREAD

**Issue by owenr34** [btjaden/TargetRNA3#7]
Is this fit to run a large amount of sRNAs at once?

Thanks for your help and great program.

**Comment by btjaden** [comment]
The program normally runs one sRNA per execution. That said, there's no reason you can't execute the program a large number of times either in parallel or in serial. If you initiate multiple parallel executions, I would suggest setting the -n_threads flag to indicate how many threads you want to use for each of the executions.

**Comment by owenr34** [comment]
Thanks so much for your response!
